### ISSUE TITLE
Add a CPE Enrichment Provider

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor#121]
**Target Audience**
The Harbor system.

**What’s the Value**
The Harbor system itself needs a CPE ID to correlate vulnerability data across enrichment sources.

**Details**
The Harbor system needs a way to correlate CPEs to PURLs because different enrichment sources in the vulnerability ecosystem use one or the other IDs. For example, Ion Channel and NVD use CPE, whereas Snyk uses PURL.

**Definition of Done**
An enrichment provider that runs each day that downloads public PURL to CPE data sources.
The enrichment provider will then attempt to resolve Harbor PURL index against the CPE index.
It should report back basic statistics (total number, percentage) regarding how many PURLs cannot be resolved to a CPE.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
