### ISSUE TITLE
GitHub Provider Post processor for projects with separate modules

### ISSUE THREAD

**Issue by qtpeters** [CMS-Enterprise/sbom-harbor#131]
The observation was made that Snyk only generates a single SBOM for all of the pom.xml files where the GH Provider generates one for each file.  What needs to happen is that all of the SBOMs are generated for every build target in a repo and then compared.  the build targets that have matching SBOMs except for the build target location need to be referred to as a single "project" and only one SBOM is stored

**Comment by ericrippetoe** [comment]
Initial research approved to identify actual solution(s) required to complete.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
