### ISSUE TITLE
Ion Channel Research

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#136]
- [ ] Where are the missing metrics we expected to see?
- [ ] Did I do something wrong (in general code review)?
- [ ] What does org_package_count mean?
- [ ] Will the SBOM endpoint include transitive dependencies?
- [ ] Dig into some errors

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
