### ISSUE TITLE
Add Xrefs to GitHub Provider data

### ISSUE THREAD

**Issue by qtpeters** [CMS-Enterprise/sbom-harbor#137]
Currently there are no Xrefs in the GitHub Provider Packages.  Now that we have the necessary models in place, we can wrap up the Provider data and put it in Prod

**Comment by ericrippetoe** [comment]
On hold waiting for API Implementation

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
