### ISSUE TITLE
Add Open Telemetry instrumentation for New Relic

### ISSUE THREAD

**Issue by talentedmrjones** [CMS-Enterprise/sbom-harbor#139]
**Target Audience**
SBOM Harbor engineering team and customer

**Details**
New Relic is the metrics, tracing, and logging platform of choice, and open telemetry is used to feed that data from the app. 

**Value Add**
Operational observability helps engineers identify issues with running the application in production. 

**Definition of Done**
As a first pass, metrics can be recorded in New Relic

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
