### ISSUE TITLE
E2E Test Automation

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor#146]
**Target Audience**

- The Harbor system
- The Harbor team

**What’s the Value**

- Provide confidence that code changes can safely be auto-promoted all the way to prod.
- Identify and fix defects earlier in the cycle, when they are less expensive to address.
- Achieve a high level of functional test coverage with a pragmatic view on cost.

**Details**

CI should prove that any code changes will be able to run against a schema that matches current production.

**Definition of Done**

 - CI uses the test GitHub org to limit the data volume required to run all pipelines and tests.
 - All tasks are run in a sequence that matches production.
 - All tasks that are currently run in a manual debug mode only, must be modified to run automatically as part of CI.
 - Once all tasks have been run, all automated tests are run, and must pass.
 - All tasks are run a second time, and data consistency checks are run to ensure that no duplication of data occurs.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
