### ISSUE TITLE
Automated Data Validation

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor#147]
**Target Audience**

- Harbor engineers
- Harbor stakeholders
- SDL team

**What’s the Value**

- Eliminate human toil and inaccuracies related to manually validating data output of automated jobs.
- Provide stakeholder transparency relative to the current quality posture of the system.
- Help operational team members more rapidly troubleshoot and identify inconsistencies between Harbor and any export targets.

**Details**

The solution should provide a way of validating the data accuracy, consistency, volume, and currency.

**Definition of Done**

- Data integrity
  - For any given SBOM prove that:
    - Harbor and the SDL have the same number of dependencies.
    - If vulnerability data exists for a given dependency, Harbor and the SDL match.
    - epssScores match
    - CPE IDs match
    - CVE IDs match
- Data volume
  - Total SBOM count matches
  - Total Package count matches by PackageKind
  - Total Vulnerability count matches
- Data currency
  - Check timestamps to ensure the SDL is being updated daily.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
