### ISSUE TITLE
Automate daily production check

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#158]
**Target Audience**
SBOM Harbor team

**What’s the Value**
Knowing the state of production. It provides insight into whether scheduled processes ran, and the volume and quality of data being injested and produced

**Details**
Will schedule a task to query DocDB, and logs, and send message to slack notifications

**Definition of Done**
That @qtpeters can stop doing manual checks

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
