### ISSUE TITLE
Create task definitions for cmsgov, cms-enterprise and enterprise-cmcs GitHub organizations  

### ISSUE THREAD

**Issue by qtpeters** [CMS-Enterprise/sbom-harbor#163]
**Description**

In order to collect Packages and SBOMs from GitHub in production, we need ECS task definitions so the tasks can be run in the cloud.

We need three new task definations:
1. One for cmsgov
2. One for cms-enterprise
3. One for enterprise-cmcs

**Comment by DerekStrickland** [comment]
Complete and verified with query

```sql
select purl, fismaId, providercreated_ts 
from SBOM_HARBOR.PUBLIC.MV_SBOM_HARBOR_FINDINGS_PROD
where provider = 'harborSyft'
```
