### ISSUE TITLE
Create, View, and Edit Vendor Products

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#168]
**Target Audience**

- SaaSG team members

**What’s the Value**

Provides SaaSG team the ability to achieve compliance with the EO.

**Details**

As a power user, I can view and manage a list of products associated with a vendors.

**Definition of Done**

- Create a Product associated with a Vendor.
- Edit the name or version
- Delete a product.
- Filter and sort the list of products for a vendor by name, version, last SBOM upload date.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
