### ISSUE TITLE
Task count should be updated as soon as task items are loaded.

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#170]
**Describe the bug**

If `TaskProvider::complete` fails, the `Task` record is never updated with the count of items.

- `TaskProviders` share a lifecycle defined by the trait, with one main section of variable logic. 
- Specifically, they vary on how they query for the batch items to process and how they process each item. 
- The `TaskProvider` trait provides default logic for inserting a `Task` record when a `Task` starts, and for updating it with summary statistics and error logging when a `Task` ends. 
- Unfortunately, if the update at the end fails, the `count` field never gets updated.
- This is useful information to have when debugging, and the `Task` should get updated with a `count` as soon as that information is available.

**To Reproduce**

Run any task locally and stop it before it completes.

**Expected behavior**

The `Task` document's `count` field should be updated in each task, as soon as the primary batch query successfully retrieves the set of items to process.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
