### ISSUE TITLE
Create a DB migration for the TaskReport

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#171]
**Target Audience**

- Harbor engineers
- Harbor open source contributors and operators.

**What’s the Value**

- Maintains portability of Harbor to any infrastructure.

**Details**

- Harbor has a DB migrations capability in the `platform` crate, but that has not yet been leveraged.
- One member of the team is currently working on observability, and has defined a mongo/docdb view that gets them the data they want from the `Task` collection.
- They are exposing the ability to query this view from the CLI so that they can hook the results into their automation.
- In order to not gate forward progress, they plan to manually create this view, however, this means that a feature of Harbor now depends on a database object that is not guaranteed by running the source alone.
- This provides an excellent use case to work on the database migrations capability so that we can ensure Harbor is portable to any developer or production environment. 

**Definition of Done**

- A database migration exists to ensure that the view in question is present
- The CLI exposes a way to manually run database migrations
- The main CLI & API binaries will shut down/log/alert if the database version does not match the expected version.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
