### ISSUE TITLE
Update application code to load configuration from dynamic secrets

### ISSUE THREAD

**Issue by DerekStrickland** [CMS-Enterprise/sbom-harbor#177]
**Description**

Now that the direnv solution is in place and can be used to dynamically load secrets in dev and CI, the application code and tests need to be updated to work one and only one way from environment variables.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
