### ISSUE TITLE
Add metadata map to Task type

### ISSUE THREAD

**Issue by qtpeters** [CMS-Enterprise/sbom-harbor#182]
**Describe the bug**
Currently, there is no way to differentiate the different tasks run by the same provider in DocDB.  This leaves the nightly production report with no way to say which organization the job was executed on.  The major issue right now is that the GitHub Provider runs on three separate organizations with no way to tell which was which. 

**To Reproduce**
Run daily report and observe that there are 3 harborSyft runs in it without being able to tell which org they ran on

**Expected behavior**
All task runs are differentiated so the report is more useful

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
